Furniro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('categories/', include('goods.urls', namespace="categories")),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),




]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('more-designs/', views.more_designs, name='more_designs')


]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

orders/models.py
from django.db import models
from goods.models import Products
from users.models import User

class OrderitemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="User", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date of order creation")
    phone_number = models.CharField(max_length=20, verbose_name="Phone number")
    requires_delivery = models.BooleanField(default=False, verbose_name="Need delivery")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Delivery address")
    payment_on_get = models.BooleanField(default=False, verbose_name="Payment on receipt")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(max_length=50, default='In processing', verbose_name="Status of order")

    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return f"Order № {self.pk} | Buyer {self.user.first_name} {self.user.last_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Product", default=None)
    name = models.CharField(max_length=150, verbose_name="Name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Cost")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Quantity")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date of sale")

    class Meta:
        db_table = "order_item"
        verbose_name = "Sold product"
        verbose_name_plural = "Sold products"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

orders/forms.py
import re
from django import forms

class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", "Self Delivery"),
            ("1", "Need Delivery"),
        ]
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'Payment with card'),
            ("1", 'Cash/on receive'),
        ]
    )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Phone number must consist of only digits")

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Wrong format of phone number")

        return data

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem

@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)
                    print(f"Cart items for user {user}: {cart_items}")

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'] == '1',
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'] == '1',
                        )
                        print(f"Order created: {order}")

                        for cart_item in cart_items:
                            product = cart_item.product
                            name = product.name
                            price = product.price
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Insufficient quantity of goods {name} available. Available - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()
                            print(f"OrderItem created for product: {product.name}, quantity: {quantity}")

                        cart_items.delete()
                        print(f"Cart items for user {user} deleted.")

                        messages.success(request, 'The order has been placed!')
                        return redirect('user:profile')
                    else:
                        messages.error(request, 'Your cart is empty.')
                        return redirect('cart:cart_detail')
            except ValidationError as e:
                messages.error(request, str(e))
                return redirect('orders:create_order')
            except Exception as e:
                print(f"An error occurred: {e}")
                messages.error(request, 'An error occurred while processing your order.')
                return redirect('orders:create_order')
        else:
            print(f"Form is not valid: {form.errors}")
            messages.error(request, 'There was an error with your form submission.')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)

    context = {
        'form': form,
        'order': True,
    }
    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Selected products</h3>
        <div class="container" id="cart-items-container">
            <!-- Cart Layout -->
            {% user_carts request as carts %}
            {% include "carts/includes/included_cart.html" %}
        </div>
    </div>
    <!-- Order details -->
    <div class="container">
        <h3 class="text-center">Order Details</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url 'orders:create_order' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">First Name*:</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name"
                                   value="{{ form.first_name.value|default_if_none:'' }}" required>
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Second Name*:</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                                   value="{{ form.last_name.value|default_if_none:'' }}" required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Phone Number*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                   value="{{ form.phone_number.value|default_if_none:'' }}" placeholder="In format: XXX-XXX-XX-XX" required>
                            {% if form.phone_number.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Delivery Way:</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                       id="id_requires_delivery_yes" value="1" {% if form.requires_delivery.value == '1' %}checked{% endif %}>
                                <label class="form-check-label" for="id_requires_delivery_yes">Need Delivery</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                       id="id_requires_delivery_no" value="0" {% if form.requires_delivery.value == '0' %}checked{% endif %}>
                                <label class="form-check-label" for="id_requires_delivery_no">Self Delivery</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Address of Delivery*:</label>
                            <textarea class="form-control" id="id_delivery_address" name="delivery_address" rows="2">{{ form.delivery_address.value|default_if_none:'' }}</textarea>
                            {% if form.delivery_address.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Payment:</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                       id="id_payment_on_get_card" value="0" {% if form.payment_on_get.value == '0' %}checked{% endif %}>
                                <label class="form-check-label" for="id_payment_on_get_card">Payment with card</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                       id="id_payment_on_get_cash" value="1" {% if form.payment_on_get.value == '1' %}checked{% endif %}>
                                <label class="form-check-label" for="id_payment_on_get_cash">Cash/on receive</label>
                            </div>
                            {% if form.payment_on_get.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.payment_on_get.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Order</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}