Furniro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('categories/', include('goods.urls', namespace="categories")),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),




]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('more-designs/', views.more_designs, name='more_designs')


]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

templates/base.html
{% load static %}
{% load goods_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Furniro </title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- CSS -->
     <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>


    <link href="https://fonts.googleapis.com/css2?family=Wittgenstein:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
  </head>


<body>
{% block nav %}
    <!-- Section Content -->
    <section>
    <!-- Background-Content -->
    <div class="container-fluid container-content">
      <!-- navbar -->
      <nav class="navbar navbar-expand-lg nav-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "main:index" %}">Furniro</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">

                <!-- Category -->
                <div class="dropdown mb-2">
                    <button class="dropdown-toggle mt-2 transparent-button"  data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </button>
                    <ul class="dropdown-menu bg-secondary" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'categories:index' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                </div>



              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "main:about" %}" id="aboutUsLink">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "user:users_cart" %}">Cart</a>


              </li>

              {% if not user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "user:login" %}">Login</a>
                  </li>

              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "user:profile" %}">My Profile</a>
                  </li>
                  {% if user.is_admin or user.is_staff %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url "admin:index" %}">Admin Panel</a>
                      </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "orders:create_order" %}">Orders</a>
                  </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url "user:logout" %}">Logout</a>
                  </li>
              {% endif %}
            </ul>
            {% block form %} {% endblock %}




{% block modal_cart %}
{% endblock %}

      </nav>


{% endblock %}


{% block content %}
{% endblock %}

{% include "includes/notifications.html" %}

<!--Section Footer -->
{% block footer %}
<section class="section-footer mt-5">
<footer class="footer">
  <div class="container">
    <div class="row pt-5">
      <div class="col-md-4">
        <h5>Contact Us</h5>
        <ul>
          <li>Email: info@example.com</li>
          <li>Phone: +1234567890</li>
          <li>Address: 123 Main St, City, Country</li>
        </ul>
      </div>
      <div class="col-md-4">
        <h5>Quick Links</h5>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">Shop</a></li>
          <li><a href="{% url "main:about" %}">About Us</a></li>

        </ul>
      </div>
      <div class="col-md-4">
        <h5>Follow Us</h5>
        <ul class="list-unstyled d-flex">
          <li class="me-2">
            <a href="https://www.facebook.com"><img src="{% static "images/icons/facebook.svg" %}" alt="Facebook" class="social-icon"></a>
          </li>
          <li class="me-2">
            <a href="https://www.twitter.com"><img src="{% static "images/icons/twitter.png" %}" alt="Twitter" class="social-icon"></a>
          </li>
          <li class="me-2">
            <a href="https://www.instagram.com"><img src="{% static "images/icons/instagram.png" %}" alt="Instagram" class="social-icon"></a>
          </li>
          <li class="me-2">
            <a href="https://www.linkedin.com"><img src="{% static "images/icons/linkedin.png" %}" alt="LinkedIn" class="social-icon"></a>
          </li>
        </ul>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-12 text-center">
        <p>&copy; 2024 Furniro</p>
      </div>
    </div>
  </div>
</footer>
</section>
{% endblock %}

  <script src="{% static '/js/jquery/jquery-3.7.0.min.js' %}"></script>
  <script src="{% static '/js/jquery-ajax.js' %}"></script>
  <script src="{% static '/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>